"""
Generate official FIFA World Cup match predictions.

Unlike the Monte Carlo simulator, this module evaluates only the real
scheduled matches of the tournament.

The statistical model is exactly the same one used by the simulator.

Output:

    outputs/official_match_predictions.csv
"""

from __future__ import annotations

import os
import pickle

import pandas as pd

from .. import config
from .. import data_loader
from .. import model
from .. import names
from .. import predict

CACHE = os.path.join(config.OUTPUT_DIR, "_tables_cache.pkl")

OUTPUT_FILE = os.path.join(
    config.OUTPUT_DIR,
    "official_match_predictions.csv",
)


def load_tables():
    """
    Loads cached model tables whenever available.
    Otherwise fits the model from historical results.
    """

    if os.path.exists(CACHE):

        with open(CACHE, "rb") as f:
            return pickle.load(f)

    df = data_loader.load_matches()

    mm = model.MatchModel().fit(df)

    tables = mm.build_tables(names.TEAMS)

    os.makedirs(config.OUTPUT_DIR, exist_ok=True)

    with open(CACHE, "wb") as f:
        pickle.dump(tables, f)

    return tables


def build_predictions(fixtures: pd.DataFrame) -> pd.DataFrame:
    """
    Builds statistical predictions for every official fixture.

    Expected input columns:

        MatchID
        Stage
        Group
        HomeTeam
        AwayTeam
    """

    tables = load_tables()

    rows = []

    for _, match_row in fixtures.iterrows():

        home = names.BY_DS[match_row.HomeTeam]
        away = names.BY_DS[match_row.AwayTeam]

        prediction = predict.build_match_prediction(

            tables=tables,

            home_idx=home.idx,

            away_idx=away.idx,

            knockout=match_row.Stage != "Group",
        )

        rows.append({

            "MatchID": match_row.MatchID,

            "Stage": match_row.Stage,

            "Group": match_row.Group,

            "HomeTeam": home.ds,

            "AwayTeam": away.ds,

            **prediction,

        })

    return pd.DataFrame(rows)


def main():

    raise NotImplementedError(
        """
Official fixtures are not available yet.

This module will consume the official bracket generated by

    official/update_official_bracket.py

once the real tournament begins.
"""
    )


if __name__ == "__main__":
    main()